// apps/grocery-list-angular/src/pages/login-page/login-page.component.ts
import { Component } from '@angular/core';
import {FormControl, FormGroup, Validators} from "@angular/forms";
import {Router} from "@angular/router";
import {AuthService} from "../../services/auth.service";

@Component({
  selector: 'login-page',
  templateUrl: './login-page.component.html',
  styleUrls: ['./login-page.component.scss']
})
export class LoginPageComponent {
  constructor(private router: Router, private authService: AuthService) {}
  form = new FormGroup({
    email: new FormControl('', [Validators.required, Validators.email]),
    password: new FormControl('', [Validators.required])
  });

  async onSubmit() {
    this.form.markAllAsTouched();
    if (this.form.valid) {
      await this.authService.signIn(this.form.value.email!, this.form.value.password!);
      await this.router.navigateByUrl('/login')
    }
  }
}

<section class="bg-gray-50">
    <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
        <div class="w-full bg-white rounded-lg shadow-lg md:mt-0 sm:max-w-md xl:p-0">
            <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                <form [formGroup]="form" (ngSubmit)="onSubmit()" class="space-y-4 md:space-y-6">
                    <div>
                        <label class="block mb-2 text-sm font-medium text-gray-900" for="email">Your email</label>
                        <input formControlName="email" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" id="email" name="email"
                               placeholder="name@company.com"
                               required type="email"/>
                        <div *ngIf="form.controls.email.touched && form.controls.email.hasError('required')" class="text-xs text-red-500">
                            Email is required
                        </div>
                        <div *ngIf="form.controls.email.touched && form.controls.email.hasError('email')" class="text-xs text-red-500">
                            Invalid email address
                        </div>
                    </div>
                    <div>
                        <label class="block mb-2 text-sm font-medium text-gray-900" for="password">Password</label>
                        <input formControlName="password" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" id="password" name="password"
                               placeholder="••••••••"
                               required
                               type="password"/>
                        <p *ngIf="form.controls.password.touched && form.controls.password.hasError('required')" class="text-xs text-red-500">Password is required</p>
                    </div>
                    <button class="w-full text-white bg-indigo-600 hover:bg-indigo-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center"
                            type="submit">
                        Sign in
                    </button>
                </form>
            </div>
        </div>
    </div>
</section>

// apps/grocery-list-react/src/pages/LoginPage.tsx
import React, {useCallback, useState} from 'react';
import {useNavigate} from "react-router-dom";
import {useAuth} from "../providers/AuthProvider";

export function LoginPage() {
    const [formState, setFormState] = useState({
        email: "",
        emailError: "",
        password: "",
        passwordError: ""
    });

    const validate = useCallback(() => {
        let isError = false;
        const emailRegex = /\S+@\S+\.\S+/;
        if (!formState.email) {
            isError = true;
            setFormState((prevState) =>
                ({...prevState, emailError: "Email is required"}));
        } else if (!emailRegex.test(formState.email)) {
            isError = true;
            setFormState((prevState) =>
                ({...prevState, emailError: "Email is invalid"}));
        }
        if (!formState.password) {
            isError = true;
            setFormState((prevState) =>
                ({...prevState, passwordError: "Password is required"}));
        }
        return isError;
    }, [formState]);

    const onChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const {name, value} = e.target;
        console.log(name, value);
        setFormState((prevProps) => ({
            ...prevProps,
            [name]: value,
            emailError: "",
            passwordError: ""
        }));
    }
    let navigate = useNavigate();
    let auth = useAuth();

    const onSubmit = useCallback((e: React.FormEvent) => {
        e.preventDefault();
        const err = validate();
        if (!err) {
            auth.signIn(formState.email, formState.password).then(() => {
                navigate("/");
            });
        }
    }, [formState, auth, validate]);
    return (
        <section className="bg-gray-50">
            <div className="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
                <div className="w-full bg-white rounded-lg shadow-lg md:mt-0 sm:max-w-md xl:p-0">
                    <div className="p-6 space-y-4 md:space-y-6 sm:p-8">
                        <form className="space-y-4 md:space-y-6" onSubmit={onSubmit} noValidate>
                            <div>
                                <label htmlFor="email"
                                       className="block mb-2 text-sm font-medium text-gray-900">Your
                                    email</label>
                                <input type="email" onChange={onChange} name="email" id="email"
                                       className="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5"
                                       placeholder="name@company.com" required/>
                                {formState.emailError && <p className="text-xs text-red-500">{formState.emailError}</p>}
                            </div>
                            <div>
                                <label htmlFor="password"
                                       className="block mb-2 text-sm font-medium text-gray-900">Password</label>
                                <input type="password" onChange={onChange} name="password" id="password"
                                       placeholder="••••••••"
                                       className="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5"
                                       required/>
                                {formState.passwordError &&
                                    <p className="text-xs text-red-500">{formState.passwordError}</p>}
                            </div>
                            <button type="submit"
                                    className="w-full text-white bg-indigo-600 hover:bg-indigo-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">Sign
                                in
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    );
}

export default LoginPage;
