// apps/grocery-list-react/src/pages/HomePage.tsx
import React, {useCallback, useState} from 'react';
import ListItem from "../components/ListItem";
import {IItem} from "../models/Item";
import AddNewItem from "../components/AddNewItem";

function HomePage() {
    const [items, setItems] = useState<IItem[]>([]);
    const onDelete = useCallback((id: string) => {
        setItems(items.filter(i => i.id !== id));
    }, [items]);
    const onAdd = useCallback((name: string) => {
        setItems([...items, { id: Date.now().toString(), name }]);
    }, [items]);
    return (
        <div className="flex items-center justify-center w-screen h-screen font-medium">
            <div className="flex flex-grow items-center justify-center h-full text-gray-600 bg-gray-100">
                <div className="max-w-full p-8 bg-white rounded-lg shadow-lg w-96">
                    { items.map(item => <ListItem key={item.id} item={item}
                                                  onDelete={onDelete} />) }
                    <AddNewItem onAdd={onAdd} />
                </div>
            </div>
        </div>
    );
}
export default HomePage;

// apps/grocery-list-angular/src/pages/home-page/home-page.component.ts
import { Component } from '@angular/core';

import {IItem} from "../../models/Item";

@Component({
  selector: 'home-page',
  templateUrl: './home-page.component.html',
  styleUrls: ['./home-page.component.scss']
})
export class HomePageComponent {
  items: IItem[] = [];

  trackById(index: number, item: IItem) {
    return item.id
  }
  onDelete(id: string) {
    this.items = this.items.filter(i => i.id !== id);
  }
  onAdd(name: string) {
    this.items.push({id: Date.now().toString(), name});
  }
}

<div class="flex items-center justify-center w-screen h-screen font-medium">
    <div class="flex flex-grow items-center justify-center h-full text-gray-600 bg-gray-100">
        <div class="max-w-full p-8 bg-white rounded-lg shadow-lg w-96">
            <list-item
                    *ngFor="let item of items; trackBy: trackById"
                    [item]="item"
                    (onDelete)="onDelete(item.id)"
            >
            </list-item>
            <add-new-item (onAdd)="onAdd($event)"></add-new-item>
        </div>
    </div>
</div>
