// apps/grocery-list-react/src/components/AddNewItem.tsx
import React, {useCallback} from 'react';
import addIconSrc from '../icons/add.svg';

interface IAddNewsItemProps {
    onAdd: (name: string) => void;
}
const AddNewItem = ({onAdd}: IAddNewsItemProps) => {
    const [value, setValue] = React.useState<string>('');
    const onChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        setValue(e.currentTarget.value);
    }, [value]);
    const onClick = useCallback(() => {
        onAdd(value);
        setValue('');
    }, [value]);
    const onKeyDown = useCallback((e: React.KeyboardEvent<HTMLInputElement>) => {
        if (e.key === 'Enter') {
            onAdd(value);
            setValue('');
        }
    }, [value, onAdd]);
    return (
        <div className="flex items-center w-full h-8 px-2 mt-2 text-sm font-medium rounded">
            <img onClick={onClick} width="20px" src={addIconSrc}/>
            <input onKeyDown={onKeyDown} value={value} onChange={onChange}
                   className="flex-grow h-8 ml-4 bg-transparent border-0 focus:outline-none font-medium"
                   type="text" placeholder="add a new item"/>
        </div>
    )
}
export default AddNewItem;

// apps/grocery-list-angular/src/components/add-new-item/add-new-item.component.ts
import {Component, EventEmitter, Output} from '@angular/core';
import {KeyboardEvent} from "react";

@Component({
    selector: 'add-new-item',
    templateUrl: './add-new-item.component.html',
    styleUrls: ['./add-new-item.component.scss']
})
export class AddNewItemComponent {
    @Output() onAdd = new EventEmitter<string>();
}

<div class="flex items-center w-full h-8 px-2 mt-2 text-sm font-medium rounded">
    <svg (click)="onAdd.emit(newItem.value);newItem.value = ''" class="w-5 h-5 text-gray-400 fill-current" fill="none" stroke="currentColor"
         viewBox="0 0 24 24" width="10px" xmlns="http://www.w3.org/2000/svg">
        <path d="M12 6v6m0 0v6m0-6h6m-6 0H6" stroke-linecap="round" stroke-linejoin="round"
              stroke-width="2"/>
    </svg>
    <input #newItem (keydown.enter)="onAdd.emit(newItem.value);newItem.value = ''" class="flex-grow h-8 ml-4 bg-transparent border-0 focus:outline-none font-medium"
           placeholder="add a new item" type="text"/>
</div>
