// apps/grocery-list-angular/src/components/list-item/list-item.component.ts
import {Component, EventEmitter, Input, Output} from '@angular/core';
import {IItem} from "../../models/Item";

@Component({
  selector: 'list-item',
  templateUrl: './list-item.component.html',
  styleUrls: ['./list-item.component.scss']
})
export class ListItemComponent {
  @Input() item!: IItem;

  @Output() onDelete = new EventEmitter();
}

<div class="flex items-center h-10 px-2 rounded cursor-pointer hover:bg-gray-100">
    <span class="text-left text-sm flex-1">{{item.name}}</span>
    <span (click)="onDelete.emit()" class="flex items-center justify-center w-5 h-5 text-transparent ml-5">
        <svg class="w-4 h-4 fill-current" id="Layer_1" version="1.1" viewBox="0 0 496.158 496.158"
             width="10px"
             xmlns="http://www.w3.org/2000/svg">
            <path d="M0,248.085C0,111.063,111.069,0.003,248.075,0.003c137.013,0,248.083,111.061,248.083,248.082
    c0,137.002-111.07,248.07-248.083,248.07C111.069,496.155,0,385.087,0,248.085z" style="fill:#E04F5F;"/>
            <path d="M383.546,206.286H112.612c-3.976,0-7.199,3.225-7.199,7.2v69.187c0,3.976,3.224,7.199,7.199,7.199
    h270.934c3.976,0,7.199-3.224,7.199-7.199v-69.187C390.745,209.511,387.521,206.286,383.546,206.286z" style="fill:#FFFFFF;"/>
        </svg>
    </span>
</div>

// apps/grocery-list-react/src/components/ListItem.tsx
import React, {useCallback} from 'react';
import deleteIconSrc from '../icons/delete.svg';
import {IItem} from "../models/Item";

interface IListItemProps {
    item: IItem;
    onDelete: (id: string) => void;
}
function ListItem({item, onDelete}: IListItemProps) {
    const onClick = useCallback(() => onDelete(item.id), []);
    return (
        <div>
            <div className="flex items-center h-10 px-2 rounded cursor-pointer hover:bg-gray-100">
                <span className="text-left text-sm flex-1">{item.name}</span>
                <span onClick={onClick} className="flex items-center justify-center w-5 h-5 text-transparent ml-5">
                    <img width="10px" src={deleteIconSrc}/>
                </span>
            </div>
        </div>
    );
}
export default ListItem;
